language: objective-c
osx_image: xcode61
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/homebrew-hhvm
  - brew tap --repair
env:
  matrix:
#    - HOMEBREW_CC=gcc-4.9 HOMEBREW_CXX=g++-4.9 OPTS="--with-gcc"
    - HOMEBREW_CC=clang HOMEBREW_CXX=clang++ OPTS=""
script:
  - brew audit hhvm
  - brew install -v hhvm --with-cotire --with-minsizerel $OPTS
matrix:
  fast_finish: true
